### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by ChefSpeciale** [GetWVKeys/getwvkeys#30]
Hi, i have an Keyerror in setup on Ubuntu server.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/getwvkeys/getwvkeys/main.py", line 58, in <module>
    from getwvkeys import config, libraries
  File "/root/getwvkeys/getwvkeys/config.py", line 29, in <module>
    SECRET_KEY = os.environ['ea6f1d7404223a7a30f94f4aa9d314e8']  # generate secret offline with os.urandom(16).hex()
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'ea6f1d7404223a7a30f94f4aa9d314e8'

i have generated it with python using:

>>> import os
>>> os.urandom(16).hex()

How can i fix this?

**Comment by Puyodead1** [comment]
🤦‍♂️
